spring:
  application:
    name: CRUD

  thymeleaf:
    layout-dialect:
      enabled: true
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/crud?useSSL=false
    username: root
    password:

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/crud?useSSL=false
    user: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
